Server:
  HttpPort: 8090
Logger:
  FileName: storage/logs/logs.log
  MaxSize: 64
  MaxBackup: 4
  MaxAge: 30
  Compress: false
  Type: single
  Level: debug
Database:
  DbConnection: mysql
  DbHost: 127.0.0.1
  DbPort: 3306
  DbDatabase: gohub
  Username: root
  Password: root
  Charset: utf8mb4
  MaxIdleConnections: 100
  MaxOpenConnections: 25
  MaxLifeSeconds: 5